import profile from "../../images/profile_1.jpg";
import diagonal from "../../images/thumbnail_4.jpg";
import sad from "../../images/thumbnail_3.jpg";
import natural from "../../images/thumbnail_2.jpg";
import happy from "../../images/thumbnail_1.jpg";


const tutorials = [
    {
        thumb: diagonal,
        title: "Diagonal Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 4,
        level: "Novice",
    },
    {
        thumb: sad,
        title: "Sad Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 2,
        level: "Intermediate",
    },
    {
        thumb: natural,
        title: "Natural Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 4,
        level: "Expert",
    },
    {
        thumb: happy,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Novice",
    },
    {
        thumb: diagonal,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Intermediate",
    },
    {
        thumb: happy,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Expert",
    },
    {
        thumb: diagonal,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Novice",
    },
    {
        thumb: happy,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Intermediate",
    },
    {
        thumb: happy,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Expert",
    },
    {
        thumb: happy,
        title: "Happy Smile",
        text: "Lorem ipsum dolor sit amet, consect adipiscing elit, sed do eiusmod.",
        author: "Phillip Massey",
        authorPic: profile,
        duration: "8 min",
        stars: 5,
        level: "Novice",
    },
];
export default tutorials;